### ISSUE TITLE
IllegalArgumentException when passing null to EmailAddressValidator.isValid(String)

### ISSUE THREAD

**Issue by PascalSchumacher** [bbottema/email-rfc2822-validator#17]
After updating from `1.1.3` to `2.1.3` it is no longer possible to pass `null` to `EmailAddressValidator.isValid(String)`:

```text
java.lang.IllegalArgumentException: Implicit NotNull argument 0 of org/hazlewood/connor/bottema/emailaddress/EmailAddressValidator.isValid must not be null
	at org.hazlewood.connor.bottema.emailaddress.EmailAddressValidator.isValid(EmailAddressValidator.java)
```

I guess this is not intended because `EmailAddressValidator.isValid(String, EnumSet<EmailAddressCriteria)` still allows `null` for the first parameter, but `isValid` and `isValidStrict` do not.

**Comment by bbottema** [comment]
Fixed the issue, but OSS Sonatype is still having network issues. I can't release 2.1.4 right now.

**Comment by PascalSchumacher** [comment]
Thanks for the quick fix! 👍

**Comment by bbottema** [comment]
2.1.4 released!

**Comment by PascalSchumacher** [comment]
Thank you very much!
